### ISSUE TITLE
em100 spi trace fails its usb interface

### ISSUE THREAD

**Issue by muthusathiyanesan** [YADRO-KNS/em100#1]
I am using em100 pro –G2 on Ubuntu Linux command line.

When I run SPI Trace, then close the SPI Trace window or use pkill to kill the process, The usb interface gets fail.

Steps to reproduce:
1.	Run “sudo em100 -D -t  --device DP145104” without quotes in termina
2.	Close the terminal about  30 seconds
3.	Run “sudo em100 –list” in another terminal
o	DP145104 device is lost

++++++
xx@yyy:~$ sudo em100 --list
Device status unknown.
Could not read from EM100 at Bus 002 Device 042
++++++++++++

Commands I use:
sudo em100 -D -t -p LOW --device DP145104
(or)
sudo em100 -D -t  --device DP145104

Close the spi trace terminal
(Or)
pkill –f DP145104

[em100SpiTraceFailure.txt](https://github.com/YADRO-KNS/em100/files/5882161/em100SpiTraceFailure.txt)

**Comment by muthusathiyanesan** [comment]
Btw, this issue is intermittent, try about 3 times to reproduce

**Comment by AlexanderAmelkin** [comment]
Sorry to say that, but this is a wrong repository to report this. This is just a fork. Please report to Coreboot team.
See https://review.coreboot.org/cgit/em100.git/
